name: Automated Check
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.PAT }}
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
        cache: 'npm'
    - run: npm ci
    - name: Create secrets file
      run: export KEY=${{ secrets.KEY }} && npm run decrypt-secrets
    - run: npm run start --tweet=true
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Automated update of feed
